### ISSUE TITLE
Recent updates appear to have broken *something*

### ISSUE THREAD

**Issue by alisterburt** [rosalindfranklininstitute/parakeet#11]
I have an environment with parakeet at 12fd851 which is working correctly, 4806096 from today passes all tests but fails to simulate for me... (and is the root cause of the failures in #10)

I think there might have been a regression, not sure if it comes from parakeet or some other dependency yet

```python
Traceback (most recent call last):
  File "/home/vol01/scarf1041/programs/miniconda3/envs/test-env-parakeet/bin/parakeet.simulate.exit_wave", line 33, in <module>
    sys.exit(load_entry_point('python-parakeet', 'console_scripts', 'parakeet.simulate.exit_wave')())
  File "/home/vol01/scarf1041/parakeet-test-setup/amplus-digital-twin/src/parakeet/command_line/simulate.py", line 259, in exit_wave
    simulation.run(writer)
  File "/home/vol01/scarf1041/parakeet-test-setup/amplus-digital-twin/src/parakeet/simulation.py", line 282, in run
    _, angle, position, image, shift = self.simulate_image(i)
  File "/home/vol01/scarf1041/parakeet-test-setup/amplus-digital-twin/src/parakeet/simulation.py", line 729, in __call__
    output_multislice = multem.simulate(system_conf, input_multislice, masker)
RuntimeError: after reduction step 1: cudaErrorInvalidDeviceFunction: invalid device function

```

**Comment by alisterburt** [comment]
corresponding versions of `python-multem` in each environment

working: `0.2.4`
not working: `0.2.6`

**Comment by alisterburt** [comment]
Installing parakeet from source at 12fd851 with `python-multem==0.2.4` didn't solve my issues unfortunately, still no working simulation

**Comment by jmp1985** [comment]
Hi Alister, sorry for the late reply. I've tried re-installing things in a number of different ways but I can't seem to reproduce this error! Do you know what version of cuda you are using?

**Comment by alisterburt** [comment]
no worries at all, strange! 

This is what I'm using (on SCARF)

```sh
module load GPUmodules
module load CUDA/11.1.1-GCC-10.2.0 
module load gcc/7.2.0
```

**Comment by jmp1985** [comment]
Thanks, I will test using that configuration now then

**Comment by alisterburt** [comment]
hero!

**Comment by jmp1985** [comment]
So everything compiles ok on scarf but I don't think I ever checked it on a GPU node on there. Do you know how to request one?

**Comment by alisterburt** [comment]
```sh
srun -p gpu -n ${NUM_CPU} --gres=gpu:${NUM_GPU} --pty /bin/bash
```
will drop you into an interactive shell on a gpu node

**Comment by jmp1985** [comment]
Hi Alister

When I logged into a GPU node as you described, for some reason parakeet couldn't see the GPU (although nvidia-smi showed one present). So I reinstalled everything from scratch whist logged into the GPU node. The following steps seemed to work for me and I was able to run some simulations:
```

# Load necessary modules
module load Anaconda3
module load GPUmodules
module load CUDA/11.1.1-GCC-10.2.0
module load gcc/7.2.0

# Lets export the compilers to use
export CXX=$(which g++)
export CUDACXX=$(which nvcc)

# Setup python3 environment
conda create --name test-env-parakeet5 python=3.8
conda activate test-env-parakeet5

# Install and test
git clone https://github.com/rosalindfranklininstitute/python-multem.git
git clone https://github.com/rosalindfranklininstitute/amplus-digital-twin.git

python -m pip install pytest pytest-cov 

pushd python-multem
git submodule update --init --recursive
python -m pip install -r requirements.txt
python setup.py develop
python -m pytest
popd

pushd amplus-digital-twin
git submodule update --init --recursive
python -m pip install -r requirements.txt
python setup.py develop # instead of python -m pip install -e .
python -m pytest
popd
```

Can you try these steps inside the GPU node and see if you get any better results?

**Comment by alisterburt** [comment]
Brill, thanks @jmp1985! Will run some tests and get back to you 👍🏼

**Comment by alisterburt** [comment]
Sorry James, I'm unable to get a working simulator following these instructions, still running into 

Let's go over things properly when we chat later on :)

```python
RuntimeError: after reduction step 1: cudaErrorInvalidDeviceFunction: invalid device function
```

**Comment by jmp1985** [comment]
Hi Alister

So I think I've managed to solve the problem, although I had to go down the rabbit hole a bit to do so... 

It looks like the issue is related to cuda versions and gpu architecture. The scarf node I ran this on had a Nvidia Tesla K80 GPU which uses the compute_37 architecture. Apparently, this is deprecated from cuda version 11. In my cmake file I had set CUDA_ARCHITECTURES = OFF which has the effect of compiling the kernels on first run on the program rather than pre-compiling them. I did this to avoid having to specify the architecture because I was running it on different machines with different GPUs and it seemed to work ok. However, I think that if the architecture is labelled as deprecated, the JIT compiler doesn't seem to work so the architecture needs to be specified explicitly. 

I have modified the CMakeLists.txt file in python-multem to look at the CMAKE_CUDA_ARCHITECTURES environment variable so that if this is set, it will compile for that. 

You can checkout what GPU you have with the following command:

`nvidia-smi --query-gpu=name --format=csv,noheader`

I've updated all the repositories and the following set of commands seem to work for me. Let me know if you have any further issues! 

```
# Setup python3 environment
conda create --name test-env-parakeet12 python=3.8
conda activate test-env-parakeet12
conda install fftw
conda install -c conda-forge gxx=9 # Latest GCC version compatible with cuda 11
conda install -c conda-forge cudatoolkit-dev

# Lets export the compilers to use
export CXX=$(which g++)
export CUDACXX=$(which nvcc)
export CMAKE_CUDA_ARCHITECTURES=37 # Set the cuda architecture for your GPU
export FFTW_ROOT=~/.conda/envs/test-env-parakeet12/

# Install and test
git clone https://github.com/rosalindfranklininstitute/amplus-digital-twin.git

python -m pip install pytest pytest-cov 

pushd amplus-digital-twin
git submodule update --init --recursive
python -m pip install -r requirements.txt
python setup.py develop
python -m pytest
popd
```

**Comment by alisterburt** [comment]
Thanks a bunch for delving into this @jmp1985 - super informative and the fix seems sane! I'll test myself this afternoon and report back. Cheers!
