### ISSUE TITLE
Installation on CentOS Linux

### ISSUE THREAD

**Issue by majtner** [rosalindfranklininstitute/parakeet#33]
Hi James,

I was trying to install parakeet on my machine:
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)

But there seems to be a problem with glibc, where Rhel 7 not have support for glibc-2.23. 

With a Docker, I get the following error:
Unable to find image 'parakeet:master' locally
docker: Error response from daemon: pull access denied for parakeet,
repository does not exist or may require 'docker login': denied:
requested access to the resource is denied.

Do you have any info if parakeet works also on other systems than Ubuntu 20.04?

Thank you.

Regards,
Tomas

**Comment by jmp1985** [comment]
Hi Tomas

I've mainly been testing on Ubuntu as that is my development environment and seems to be the only linux option on github workflows (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

There shouldn't be any reason why it can't compile on CentOS; however, you may need updated versions of some packages. I would try using the latest version of GCC and CUDA that you have access to. For example, I just compiled on CentOS 7 with the following commands and it seemed to work fine. This was installed on a machine at Diamond which uses the module load system. I used GCC version 10.2.0 and CUDA version 11.7

```
module load GCC/10
module load cuda/11.7
module load Python3

export CXX=$(which g++)
export CUDACXX=$(which nvcc)

python3 -m venv env
source env/bin/activate
python -m pip install git+https://github.com/rosalindfranklininstitute/parakeet.git@master
```

With Docker, how did you try to run and install the docker image. If you want to use a container, I would recommend trying the singularity container which you can download as follows:

```
singularity build parakeet.sif docker://ghcr.io/rosalindfranklininstitute/parakeet:master
```

I hope this helps! Let me know if you have any more issues!

Best wishes
James
