### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by MohamadHarastani** [rosalindfranklininstitute/parakeet#41]
Hi @jmp1985 
I have been testing parakeet and I found a couple of bugs.
1- parakeet.analyse.average_all_particles does not generate the correct average when the detector pixel size is not equal to 1. The particles are extracted using the locations in angstroms instead of pixels. I believe that a simple division by the pixel size would sort out this problem.
2- parakeet.metadata.export gives errors. I haven't been able to use it, so I wrote some scripts to export what I need.  
3- parakeet.config.show does not work (it shows nothing). Since there is some manual editing of the config file, this API can be useful to check that the manual editing is compatible with yaml.
4- parakeet.analyse.reconstruct gives wrong results with option -d cpu. The reconstruction works, but gives wrong results. 
Cheers
Mohamad

**Comment by jmp1985** [comment]
Hi Mohamad

I have gone through the issues and fixed each in turn.
1. parakeet.analyse.average_all_particles should now work properly with different pixel sizes
2. parakeet.metadata.export doesn't throw errors now. Perhaps we can merge some of the export code in your scripts to improve the output here as well.
3. parakeet.config.show now prints the config contents
4. parakeet.analyse.reconstruct should now work with the CPU.

I've pushed a release with the latest changes.

Thank you for testing and highlighting these issues! Let's discuss some more on Friday.

Best wishes
James

**Comment by MohamadHarastani** [comment]
Thanks James!
See you on Friday

Mohamad
