### ISSUE TITLE
Problem with "extended_header" in parakeet.export

### ISSUE THREAD

**Issue by majtner** [rosalindfranklininstitute/parakeet#49]
Hi James,

I am using parakeet v.0.4.3. and I have issues converting .h5 file to .mrc file using parakeet.export. I am getting an error in 
"io.py", line 606, in __init__
    self.handle = mrcfile.new_mmap(
TypeError: new_mmap() got an unexpected keyword argument 'extended_header'

When I tried to run the same script (from parakeet.sample.new until parakeet.export) using parakeet v.0.3.0., it worked fine for me.
But for this new version, even when I tried converting with eman2, it fails with a RuntimeError.
Do you have any idea, how can I export it to .mrc?

Thanks in advance!
Tomas

**Comment by jmp1985** [comment]
Hi @majtner 

There was an update to the ccpem mrcfile library that allows more efficient creation of large files by passing the extended_header keyword to the new_mmap function. I believe that this functionality was added in v1.4.0 of the mrcfile library. 

To fix this issue try updating the mrcfile package. You can probably do this by typing "pip install -U mrcfile". 

Let me know if that works!

Best wishes
James
